import React from 'react';
import { DenialClaim } from '../types/claims';

interface LegalStudioPageProps {
  selectedClaim: DenialClaim;
}

export const LegalStudioPage: React.FC<LegalStudioPageProps> = ({
  selectedClaim
}) => {
  // Real File Generator & Instant Browser Download
  const handleRealFileDownload = () => {
    const documentContent = `========================================================================================
SHIVAM MULTI-SPECIALTY HOSPITAL · NAGPUR
(NABH Accredited · Rohini Network Registry ID: ROHD-NAG-88291 · 180 Beds)
Medical Superintendent Office · Department of Clinical Denial Resolution
========================================================================================

CLAIM IDENTIFIER:       ${selectedClaim.id}
PATIENT NAME:           ${selectedClaim.patientName} (Age: ${selectedClaim.age}, Gender: ${selectedClaim.gender})
ABHA IDENTIFIER:        ${selectedClaim.abhaId}
INSURANCE / TPA:        ${selectedClaim.tpaName}
POLICY NUMBER:          ${selectedClaim.policyNo}
PROCEDURE PERFORMED:    ${selectedClaim.procedureName} (ICD-10: ${selectedClaim.icd10})
DATES OF ADMISSION:     ${selectedClaim.admissionDate} to ${selectedClaim.dischargeDate}
TOTAL BILLED:           Rs. ${selectedClaim.billedAmount.toLocaleString('en-IN')}
REPUDIATED SUM:         Rs. ${selectedClaim.deniedAmount.toLocaleString('en-IN')}
REJECTION REASON:       ${selectedClaim.denialCode} - ${selectedClaim.denialReasonRaw}
STATUTORY DEADLINE:     ${selectedClaim.deadlineDays} Days Remaining in 15-Day IRDAI Window

----------------------------------------------------------------------------------------
SECTION 1: FORMAL STATUTORY APPEAL TO TPA GRIEVANCE REDRESSAL OFFICER (ENGLISH)
----------------------------------------------------------------------------------------

${selectedClaim.appealLetterEn}

----------------------------------------------------------------------------------------
SECTION 2: CLINICAL SUMMARY & JUSTIFICATION (HINDI / हिन्दी)
----------------------------------------------------------------------------------------

${selectedClaim.clinicalSummaryHi}

----------------------------------------------------------------------------------------
SECTION 3: STATUTORY PRECEDENT ATTACHED
----------------------------------------------------------------------------------------
GOVERNING STATUTE:     ${selectedClaim.matchedCitation}
VERIFICATION HASH:     SHA256: 8f4e9f6b27e62570db33 | DPDP Act 2023 Compliant Anonymized
PHYSICIAN STAMP:       Dr. Anjali Desai, MS (Gen Surg) · Reg No: MMC-2008/04/1192

========================================================================================
Generated by PRATIGYA Healthcare Platform · Autonomous 7-Node Denial Recovery Desk
========================================================================================`;

    const blob = new Blob([documentContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `PRATIGYA_Appeal_${selectedClaim.id}_${selectedClaim.patientName.replace(/\s+/g, '_')}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="cream-card" style={{ padding: 28 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24, flexWrap: 'wrap', gap: 16 }}>
        <div>
          <h2 className="serif-heading" style={{ margin: 0, fontSize: 22, fontWeight: 700, color: '#0F2038' }}>
            📜 Bilingual Regulatory Appeal Studio
          </h2>
          <p style={{ margin: '4px 0 0 0', fontSize: 13, color: '#60646C' }}>
            Claim ID: <span style={{ color: '#E05A1B', fontFamily: 'monospace', fontWeight: 700 }}>{selectedClaim.id}</span> · Patient: <strong>{selectedClaim.patientName}</strong> · Disputed: <strong style={{ color: '#C5221F' }}>₹{selectedClaim.deniedAmount.toLocaleString('en-IN')}</strong>
          </p>
        </div>
        <button
          className="btn-luxury-saffron"
          onClick={handleRealFileDownload}
          style={{ boxShadow: '0 4px 15px rgba(224, 90, 27, 0.35)' }}
        >
          📥 Download Formatted Appeal Package (.doc)
        </button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 0.8fr', gap: 24 }}>
        {/* English Formal Legal Petition */}
        <div className="cream-card" style={{ padding: 24, background: '#FFFFFF' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 14, borderBottom: '1px solid #E8E2D9', paddingBottom: 10 }}>
            <span style={{ fontSize: 12, fontWeight: 800, color: '#0F2038', textTransform: 'uppercase' }}>
              1. Formal Statutory Appeal to TPA (English)
            </span>
            <span style={{ fontSize: 11, color: '#8B909A' }}>IRDAI Master Circular 2024</span>
          </div>
          <textarea
            rows={16}
            value={selectedClaim.appealLetterEn}
            readOnly
            style={{ width: '100%', background: '#FAF8F5', border: '1px solid #E8E2D9', borderRadius: 8, padding: 14, color: '#1C2024', fontSize: 12, fontFamily: 'monospace', lineHeight: 1.6, resize: 'none' }}
          />
        </div>

        {/* Hindi Clinical Summary */}
        <div className="cream-card" style={{ padding: 24, background: '#FFF9F5', border: '1px solid #FFD9C7' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 14, borderBottom: '1px solid #FFD9C7', paddingBottom: 10 }}>
            <span style={{ fontSize: 12, fontWeight: 800, color: '#E05A1B', textTransform: 'uppercase' }}>
              2. Clinical Summary (हिन्दी / Hindi)
            </span>
            <span style={{ fontSize: 11, color: '#E05A1B', fontWeight: 600 }}>चिकित्सा सारांश</span>
          </div>
          <p style={{ fontSize: 14, color: '#662208', lineHeight: 1.8, background: '#FFFFFF', padding: 16, borderRadius: 8, border: '1px solid #FFE4D6' }}>
            {selectedClaim.clinicalSummaryHi}
          </p>

          <div style={{ marginTop: 20, padding: 16, background: '#FFFFFF', borderRadius: 8, border: '1px solid #E8E2D9' }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: '#0F2038', marginBottom: 6 }}>
              Attached Precedent:
            </div>
            <div style={{ fontSize: 12, color: '#0E7B6C', fontWeight: 600 }}>
              {selectedClaim.matchedCitation}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
